spring:
  datasource:
    username: dummy
    password: password
    url: jdbc:mysql://192.168.1.149:3306/Agencia
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.149:8761/eureka
